In [1]:
import pandas as pd

In [9]:
path = 'C:/juehyeon/aice_test/materials/datasets/'
data = pd.read_csv(path + 'winequality-white.csv')

In [10]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,quality,alcohol
0,7.0,0.27,0.36,20.7,45.00,45.0,170.0,1.001,3.00,0.45,6,"R$ 45.512,00"
1,6.3,0.30,0.34,1.6,49.00,14.0,132.0,994.000,3.30,0.49,6,"R$ 45.421,00"
2,8.1,0.28,0.40,6.9,0.05,30.0,97.0,9.951,3.26,0.44,6,"R$ 45.301,00"
3,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"
4,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"

In [11]:
quality_data = data['quality']

In [13]:
quality_data.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

In [14]:
## 여러 열을 선택
selected_data = data[['quality', 'pH']]
selected_data.head()

   quality    pH
0        6  3.00
1        6  3.30
2        6  3.26
3        6  3.19
4        6  3.19

In [16]:
# 범위 지정
top_10_rows = data[:10]
top_10_rows

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,quality,alcohol
0,7.0,0.27,0.36,20.7,45.00,45.0,170.0,1.001,3.00,0.45,6,"R$ 45.512,00"
1,6.3,0.30,0.34,1.6,49.00,14.0,132.0,994.000,3.30,0.49,6,"R$ 45.421,00"
2,8.1,0.28,0.40,6.9,0.05,30.0,97.0,9.951,3.26,0.44,6,"R$ 45.301,00"
3,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"
4,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"
5,8.1,0.28,0.40,6.9,0.05,30.0,97.0,9.951,3.26,0.44,6,"R$ 45.301,00"
6,6.2,0.32,0.16,7.0,45.00,30.0,136.0,9.949,3.18,0.47,6,"R$ 45.452,00"
7,7.0,0.27,0.36,20.7,45.00,45.0,170.0,1.001,3.00,0.45,6,"R$ 45.512,00"
8,6.3,0.30,0.34,1.6,49.00,14.0,132.0,994.000,3.30,0.49,6,"R$ 45.421,00"
9,8.1,0.22,0.43,1.5,44.00,28.0,129.0,9.938,3.22,0.45,6,"R$ 11,00"

In [17]:
# 특정 행, 열 선택 : iloc 또는 loc 사용
## iloc : 인덱스 기준 데이터 선택 
value = data.iloc[0,1] # 첫 번째 행의 두 번째 열 데이터 
print(value)

0.27

In [19]:
## loc : 행과 열 이름을 기준으로 데이터 선택
value = data.loc[0, 'quality'] # 첫 번째 행의 'quality'열의 값 선택
print(value)

6

In [23]:
# 데이터 조건으로 검색

## 단일 조건 
### ex) 품지링 7이상인 데이터 선택
high_quality = data[data['quality'] >= 7]
print(high_quality.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
13            6.6              0.16         0.40             1.5       44.0
15            6.6              0.17         0.38             1.5       32.0
17            6.2              0.66         0.48             1.2       29.0
20            6.2              0.66         0.48             1.2       29.0
21            6.4              0.31         0.38             2.9       38.0

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
13                 48.0                 143.0    9.912  3.54       0.52
15                 28.0                 112.0    9.914  3.25       0.55
17                 29.0                  75.0    9.892  3.33       0.39
20                 29.0                  75.0    9.892  3.33       0.39
21                 19.0                 102.0    9.912  3.17       0.35

    quality       alcohol
13        7  R$ 45.394,00
15        7  R$ 45.393,00
17        8  R$ 45.516,00
20        8  R$ 45.516,00
21        7      R$ 11,00

In [27]:
## 다중 조건
### ex) 품질이 8이상이고 pH가 3이상인 데이터 선택
high_quality_alcohol = data[(data['quality'] >= 8) & (data['pH'] >= 3)]
print(high_quality_alcohol.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
17            6.2              0.66         0.48             1.2       29.0
20            6.2              0.66         0.48             1.2       29.0
22            6.8              0.26         0.42             1.7       49.0
68            6.7              0.23         0.31             2.1       46.0
74            6.7              0.23         0.31             2.1       46.0

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
17                 29.0                  75.0    9.892  3.33       0.39
20                 29.0                  75.0    9.892  3.33       0.39
22                 41.0                 122.0  993.000  3.47       0.48
68                 30.0                  96.0    9.926  3.33       0.64
74                 30.0                  96.0    9.926  3.33       0.64

    quality       alcohol
17        8  R$ 45.516,00
20        8  R$ 45.516,00
22        8  R$ 45.422,00
68        8  R$ 45.483,00
74        8  R$ 45.483,00