In [25]:
import pandas as pd
path = 'C:/juehyeon/aice_test/materials/datasets/'
df = pd.read_csv(path + 'heart.csv')

In [3]:
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', '최대 심박수',
              '운동유발협심증', 'ST 우울증', '운동후 ST경사', '주요혈관수', '결함유형', '심장질환여부']

In [4]:
# 그룹화와 집계 
## 성별을 기준으로 데이터 그룹화
groupped= df.groupby('성별')
groupped.size()

성별
0     96
1    207
dtype: int64

In [5]:
## 성별별 주요 열의 평균 집계
groupped_mean = groupped.mean()
print(groupped_mean)

           나이      흉통유형       안정시혈압       콜레스테롤     공복혈당       심전도  \
성별
0   55.677083  1.041667  133.083333  261.302083  0.12500  0.572917
1   53.758454  0.932367  130.946860  239.289855  0.15942  0.507246

        최대 심박수   운동유발협심증    ST 우울증  운동후 ST경사     주요혈관수      결함유형    심장질환여부
성별
0   151.125000  0.229167  0.876042  1.427083  0.552083  2.125000  0.750000
1   148.961353  0.371981  1.115459  1.386473  0.811594  2.400966  0.449275

In [6]:
## 여러 집계 함수 사용 : agg()
### agg() : 여러 열에 다양한 집계 함수 동시 적용, 딕셔너리 형태로 열 이름과 함수 목록 지정
groupped_stats = groupped.agg({
    '나이' : ['max' , 'min'],
    '콜레스테롤' : ['mean', 'std']
})
print(groupped_stats)

    나이           콜레스테롤
   max min        mean        std
성별
0   76  34  261.302083  65.088946
1   77  29  239.289855  42.782392

In [7]:
## 다중 그룹화
groupped_multi = df.groupby(['성별', '흉통유형']).mean()
groupped_multi

                나이       안정시혈압       콜레스테롤      공복혈당       심전도      최대 심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증    ST 우울증  운동후 ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

In [8]:
# Pivot Table 조작 : 특정 기준에 따라 데이터를 요약하거나 변환하는데 사용하는 도구
## 1. pivot table 생성
pivot = df.pivot_table(index = '성별', columns = '흉통유형', values = '최대 심박수', aggfunc = 'mean')
### 해석 ) 성별을 인덱스로 지정, 흉통유형을 열로 지정, 최대 심박수 값을 피벗 테이블에서 요약 데이터로 사용, 최대 심박수의 평균값 계산
pivot

흉통유형           0           1           2           3
성별
0     145.282051  162.833333  151.800000  149.500000
1     138.759615  162.187500  158.173077  157.315789

In [10]:
## 2. 집계함수 적용
pivot = df.pivot_table(index = '성별', columns = '흉통유형', values = '최대 심박수', aggfunc = ['mean', 'max'])
pivot

            mean                                      max
흉통유형           0           1           2           3    0    1    2    3
성별
0     145.282051  162.833333  151.800000  149.500000  182  192  179  171
1     138.759615  162.187500  158.173077  157.315789  186  202  194  190

In [11]:
## 3. 다중 인덱스 피벗 테이블
pivot_multi_index = df.pivot_table(index = ['성별', '흉통유형'] , values = '최대 심박수', aggfunc = 'mean')
pivot_multi_index

             최대 심박수
성별 흉통유형
0  0     145.282051
   1     162.833333
   2     151.800000
   3     149.500000
1  0     138.759615
   1     162.187500
   2     158.173077
   3     157.315789

In [12]:
'''
Pivot Table 주요 옵션
1) index : 행 인덱스로 설정할 열
2) columns : 열로 설정할 데이터
3) values : 요약할 데이터
4) aggfunc : 집계 함수 지정
5) fill_value : 결측값을 대체할 값 
'''

'\nPivot Table 주요 옵션\n1) index : 행 인덱스로 설정할 열\n2) columns : 열로 설정할 데이터\n3) values : 요약할 데이터\n4) aggfunc : 집계 함수 지정\n5) fill_value : 결측값을 대체할 값 \n'

In [20]:
## 4. pivot table 결측값 처리
data = {
    '성별' : ['남성', '여성', '남성', '여성'],
    '흉통유형' : [1,2,3,1],
    '최대 심박수' : [150, 160, 155, 145]
}
df = pd.DataFrame(data)
print('\n 원본 데이터 프레임 \n' ,df)

### pivot table 생성
pivot = df.pivot_table(index = '성별', columns = '흉통유형', values = '최대 심박수', aggfunc = 'mean')
print('\n 원본 pivot table \n' ,pivot)

 원본 데이터 프레임
    성별  흉통유형  최대 심박수
0  남성     1     150
1  여성     2     160
2  남성     3     155
3  여성     1     145

 원본 pivot table
 흉통유형      1      2      3
성별
남성    150.0    NaN  155.0
여성    145.0  160.0    NaN

In [21]:
### 결측값을 특정값으로 대체하기
pivot_filled = df.pivot_table(index = '성별' , columns = '흉통유형', values = '최대 심박수', aggfunc = 'mean', fill_value = 0)
print('결측값을 0으로 대체 \n' , pivot_filled)

결측값을 0으로 대체
 흉통유형      1      2      3
성별
남성    150.0    0.0  155.0
여성    145.0  160.0    0.0

In [23]:
### 평균값으로 대체 
pivot_mean_filled =  pivot.apply(lambda x: x.fillna(x.mean()), axis = 0)
pivot_mean_filled

흉통유형      1      2      3
성별
남성    150.0  160.0  155.0
여성    145.0  160.0  155.0

In [24]:
### 특정값으로 설정
pivot_setting_value = pivot.fillna(999)
pivot_setting_value

흉통유형      1      2      3
성별
남성    150.0  999.0  155.0
여성    145.0  160.0  999.0

In [27]:
# 인덱스와 컬럼 계층 변경
## 인덱스 계층 : 여러 개의 인덱스 레벨을 사용해 데이터를 계층적으로 관리하는 방식 
## 컬럼 계층 : 여러 개의 컬럼 레벨을 사용해 데이터를 다차원적으로 표현하는 방식
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', '최대 심박수',
              '운동유발협심증', 'ST 우울증', '운동후 ST경사', '주요혈관수', '결함유형', '심장질환여부']

In [28]:
## 1. 그룹화 후 다중 인덱스 생성
groupped = df.groupby(['성별', '흉통유형']).mean()
groupped

                나이       안정시혈압       콜레스테롤      공복혈당       심전도      최대 심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증    ST 우울증  운동후 ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

In [29]:
## 2. 다중 인덱스 초기화
groupped_reset = groupped.reset_index()
groupped_reset

,성별,흉통유형,나이,안정시혈압,콜레스테롤,공복혈당,심전도,최대 심박수,운동유발협심증,ST 우울증,운동후 ST경사,주요혈관수,결함유형,심장질환여부
0,0,0,57.256410,138.589744,267.538462,0.128205,0.538462,145.282051,0.461538,1.356410,1.179487,0.820513,2.282051,0.461538
1,0,1,51.944444,128.055556,251.444444,0.111111,0.555556,162.833333,0.111111,0.461111,1.666667,0.555556,2.000000,0.888889
2,0,2,54.971429,127.885714,261.057143,0.114286,0.600000,151.800000,0.057143,0.474286,1.571429,0.257143,2.028571,0.971429
3,0,3,63.250000,147.500000,247.000000,0.250000,0.750000,149.500000,0.000000,1.575000,1.500000,0.500000,2.000000,1.000000
4,1,0,55.105769,129.557692,243.605769,0.125000,0.451923,138.759615,0.596154,1.393269,1.288462,1.019231,2.509615,0.201923
5,1,1,51.031250,128.593750,241.031250,0.093750,0.656250,162.187500,0.062500,0.234375,1.687500,0.343750,2.218750,0.781250
6,1,2,52.538462,132.057692,231.134615,0.250000,0.596154,158.173077,0.173077,1.015385,1.461538,0.807692,2.326923,0.673077
7,1,3,54.315789,139.473684,235.052632,0.210526,0.315789,157.315789,0.210526,1.352632,1.210526,0.473684,2.315789,0.631579

In [31]:
## 3. 다중 컬럼 pivot table 생성
pivot = df.pivot_table(index = '성별', columns =  ['흉통유형', '운동후 ST경사'], values = '최대 심박수', aggfunc = 'mean')
pivot

흉통유형           0                              1                           2  \
운동후 ST경사       0           1           2      0           1       2       0
성별
0         146.00  139.000000  161.400000    NaN  160.500000  164.00  160.00
1         126.75  128.431034  157.052632  168.5  139.833333  167.25  171.25

흉통유형                                  3
운동후 ST경사           1           2      0           1           2
성별
0         149.153846  153.047619  114.0         NaN  161.333333
1         147.250000  164.107143  147.5  159.272727  157.000000

In [35]:
## 4. 다중 컬럼 계층 전환
pivot_stack = pivot.stack(future_stack=True)
pivot_stack

흉통유형                  0           1           2           3
성별 운동후 ST경사
0  0         146.000000         NaN  160.000000  114.000000
   1         139.000000  160.500000  149.153846         NaN
   2         161.400000  164.000000  153.047619  161.333333
1  0         126.750000  168.500000  171.250000  147.500000
   1         128.431034  139.833333  147.250000  159.272727
   2         157.052632  167.250000  164.107143  157.000000